Re-updated to LSTS/imc@d017446 and LSTS/imcjava@a541dba.
The previous was compiled with Java 11, and running on Java 8 it will be problems.
See https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip